from player import *
if __name__ == "__main__":
    red= Player("Ned Stark")
    blue= Player("Arthur Dayne")

    red.attack(blue)
    red.big_attack(blue)
    red.big_attack(blue)
    blue.attack(red)
    blue.attack(red)
    blue.attack(red)
    blue.buy_med(BigMed)
    blue.take_med(BigMed)
    red.buy_med(SmallMed)
    red.buy_med(SmallMed)
    red.take_med(SmallMed)
    red.take_med(SmallMed)
    blue.attack(red)
    blue.attack(red)
    blue.attack(red)
    blue.attack(red)
    blue.big_attack(red)
    blue.big_attack(red)
    blue.big_attack(red)
    blue.big_attack(red)
    blue.big_attack(red)